DELTO-266: s3 scripts
Deltologic/delto-scripts pull request #5
Opened 2022-08-15 18:45 UTC by jakubriegel

2022-08-16 07:16 UTC, gordon502 commented on aws-s3/count-all-objects/readme.md
> +Before runnig the script, you need to fill in the AWS connectin information:
Może będę się czepiał, ale w opisach/komentarzach pozjadało ci sporo znaków, dalej będę oznaczał kolejne miejsca krótkim komentarzem

2022-08-16 07:17 UTC, gordon502 commented on aws-s3/count-all-objects/readme.md
> +Script template for counting all S3 objects in seleted bucket.
Może będę się czepiał, ale w opisach/komentarzach pozjadało ci sporo znaków, dalej będę oznaczał kolejne miejsca krótkim komentarzem

2022-08-16 07:17 UTC, gordon502 commented on aws-s3/count-all-objects/readme.md
> +Before runnig the script, you need to fill in the AWS connectin information:
typo

2022-08-16 07:17 UTC, gordon502 commented on aws-s3/count-all-objects/readme.md
> +In oder to download the dependencies type:
typo

2022-08-16 07:17 UTC, gordon502 commented on aws-s3/count-all-objects/readme.md
> +In oder to download start the scripts type:
typo

2022-08-16 07:18 UTC, gordon502 commented on aws-s3/count-all-objects/readme.md
> +In oder to download the dependencies type:
typo

2022-08-16 07:19 UTC, gordon502 commented on aws-s3/delete-objects-concurrent/readme.md
> +Before runnig the script, you need to fill in the AWS connectin information:
typo

2022-08-16 07:20 UTC, gordon502 commented on aws-s3/delete-objects-concurrent/readme.md
> +In oder to download the dependencies type:
typo

2022-08-16 07:20 UTC, gordon502 commented on aws-s3/delete-objects-concurrent/readme.md
> +In oder to download start the scripts type:
typo

2022-08-16 07:21 UTC, gordon502 commented on aws-s3/delete-objects/readme.md
> +Before runnig the script, you need to fill in the AWS connectin information:
typo

2022-08-16 07:21 UTC, gordon502 commented on aws-s3/delete-objects/readme.md
> +In oder to download the dependencies type:
typo

2022-08-16 07:21 UTC, gordon502 commented on aws-s3/delete-objects/readme.md
> +In oder to download start the scripts type:
typo

2022-08-16 07:35 UTC, gordon502 commented on aws-s3/migrate-to-different-s3/readme.md
> +Before runnig the script, you need to fill in the AWS connection information:
typo

2022-08-16 07:35 UTC, gordon502 commented on aws-s3/migrate-to-different-s3/readme.md
> +In oder to download the dependencies type:
typo

2022-08-16 07:35 UTC, gordon502 commented on aws-s3/migrate-to-different-s3/readme.md
> +In oder to download start the scripts type:
typo

2022-08-16 07:46 UTC, gordon502 requested changes
Po naprawieniu "typos" z poprzednich komentarzy wszystko będzie git

2022-08-16 07:46 UTC, gordon502 commented on aws-s3/count-all-objects/script.js
> +        const page = await s3.listObjectsV2({Bucket: config.bucket, ContinuationToken: token, MaxKeys: maxKeys}).promise()
nie można po prostu bez awaita wykonać funkcje listObjectsV2 bez zrzucania jej do Promisa?

2022-08-16 07:46 UTC, gordon502 commented on aws-s3/delete-objects/script.js
> +            const worker = workers.pop()
Nie lepiej jest tutaj wziąć pierwszy element tablicy metodą shift()?

2022-08-16 10:59 UTC, jakubriegel commented on aws-s3/count-all-objects/script.js
> +        const page = await s3.listObjectsV2({Bucket: config.bucket, ContinuationToken: token, MaxKeys: maxKeys}).promise()
Nie można tak zrobić, bo `listObjectsV2` jest aynchroniczne i albo się robi z niego promisa albo się dodaje callbacka

2022-08-16 11:00 UTC, jakubriegel commented on aws-s3/delete-objects/script.js
> +            const worker = workers.pop()
Zdecydowanie lepiej :D Poprawiam

2022-08-16 12:50 UTC, gordon502 commented on aws-s3/count-all-objects/script.js
> +        const page = await s3.listObjectsV2({Bucket: config.bucket, ContinuationToken: token, MaxKeys: maxKeys}).promise()
Gdzie znalazłeś informację, że to jest asynchroniczne? Sprawdziłem dokumentacje i metoda [_listObjectsV2_](https://github.com/aws/aws-sdk-js/blob/9cca4f98ab672630f852a5ede273554e7829da68/clients/s3.d.ts#L523) i zwraca typ [_Request_](https://github.com/aws/aws-sdk-js/blob/master/lib/http_request.d.ts)
```javascript
  listObjectsV2(params: S3.Types.ListObjectsV2Request, callback?: (err: AWSError, data: S3.Types.ListObjectsV2Output) => void): Request<S3.Types.ListObjectsV2Output, AWSError>;
```

2022-08-16 13:00 UTC, gordon502 commented on aws-s3/count-all-objects/script.js
> +        const page = await s3.listObjectsV2({Bucket: config.bucket, ContinuationToken: token, MaxKeys: maxKeys}).promise()
Sama funkcja nie jest asynchroniczna, bo zwraca typ [_Request_](https://github.com/aws/aws-sdk-js/blob/master/lib/http_request.d.ts),
```javascript
  listObjectsV2(params: S3.Types.ListObjectsV2Request, callback?: (err: AWSError, data: S3.Types.ListObjectsV2Output) => void): Request<S3.Types.ListObjectsV2Output, AWSError>;
```
ale faktycznie żeby dostać się do wyniku trzeba skorzystać z callbacka, albo jak u Ciebie zrzucić to do Promisa.

Także ostatecznie jest spoko.

2022-08-17 09:44 UTC, gordon502 approved these changes

2022-08-17 09:45 UTC, merged